first worked version v.1.0.0
walerikq/Hospital pull request #1
Opened 2022-12-16 10:07 UTC by walerikq

2022-12-18 19:17 UTC, zzaharovs requested changes

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/Dto/PatientDto.java
> +    private Byte age;
А если челу 130?)))
Я бы не парился и делал Integer, экономия памяти не настолько большая чтобы за это париться

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientRepo.java
> +    private Map<Integer,Patient> patientList = new HashMap<>();
Тогда скорее patientMap

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientRepo.java
> +    public Map<Integer, Patient> getPatientsWithStatus(@NotNull PatientsStatus patientsStatus) {
Три момента
1. Тут не обязательно возвращать мапу, лучше вернуть лист
2. Тебе нет нужды использовать цикл со счетчиком. Рекомендую подумать воот в эту сторону
        patientMap.values().stream()
                .filter(x -> (тут какое то твое условие))
                .collect(Collectors.toList());

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientRepo.java
> +        return patientList;
тут тоже достаточно вернуть только лист через метод .values

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/service/PatientService.java
> +        if (patientDto.getAge() > 0){
а если эйдж у пациента 0? новорожденный

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/service/PatientService.java
> +        if (patientDto.getAge() > 0){
И еще момент - если эйдж будет null у тебя тут в пациента null запишется

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/service/PatientService.java
> +        Patient patient = patientRepo.getPatientById(patientDto.getId());
Непонятно зачем ты его здесь вытащил. У тебя дальше используется только репозиторий, этот объект ты не трогаешь

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/service/PatientService.java
> +
Вообще я бы в этом методе вытащил пациента из БД, и поэтапно по одному полю бы сеттил в него значения из dto если в dto они не null

А в конце вызвал бы один метод репозитория savePatient куда передается пациент целиком

У тебя получается что ты БД дергаешь 6 раз чтобы каждый раз сохранить в нее одного пациента
Логичнее будет если ты ее дернешь два - чтобы вытащить пациента и чтобы сохранить его обратно обновленного

2022-12-18 19:17 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientRepo.java
> +     */
Это все я бы заменил на один метод savePatient()

2022-12-20 11:20 UTC, walerikq commented on src/main/java/com/walerikq/hospital/service/PatientService.java
> +        Patient patient = patientRepo.getPatientById(patientDto.getId());
Я тоже это после коммита заметил, это от старой реализации осталось

2022-12-22 13:36 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientMap.java
> +
тут можно просто return без объявления переменной
ну и закомменченное я бы почистил

2022-12-22 13:36 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientMap.java
> +public class PatientMap {
Класс удачнее назвать PatientRepository
Тебе же по сути не важно как он хранит данные и откуда берет

2022-12-22 13:36 UTC, zzaharovs commented on src/main/java/com/walerikq/hospital/repository/PatientMap.java
> +    public Map<Integer, Patient> getAllPatients() {
Тут я бы возвращал лист
Просто вэльюс.стрим.коллект
Кстати по джава конвеншн после стрима вызов каждой функции с новой строчки
.values().stream()
.collect()

2022-12-22 16:04 UTC, zzaharovs approved these changes

2023-03-12 10:11 UTC, merged